### ISSUE TITLE
compile error when selecting use MQTT Subscribe

### ISSUE THREAD

**Issue by Bitbanger1900** [nopnop2002/esp-idf-mqtt-camera#8]
Hi,

Thanks for writing this program! Very usefull and a great idea!

I get a compile error when i  select the shutter option use MQTT Subscribe:
Compiling with GPIO or Enter is error free.

error:
espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/main/libmain.a(mqtt_sub.c.obj):(.literal.mqtt_event_handler+0xc): undefined reference to `status_event_group'

-  git clone https://github.com/espressif/esp-idf.git --branch release/v4.4
-  git submodule update --init --recursive
-  run the install.sh and source the export.sh
-  idf.py menuconfig etc.

Regards,
Bitbanger.

**Comment by nopnop2002** [comment]
Thank you for reporting.

I fixed it.

Happy new year.

**Comment by Bitbanger1900** [comment]
Working!

Thanks and also a Happy new Year!!
